<?php
	/* $Id$ */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageRight
	{
		private $pageId = null;
		
		private $rightId = null;
		
		private $redirectPageId = null;
		
		/**
		 * @return PageRightDA
		 */
		public static function da()
		{
			return PageRightDA::me();
		}
		
		public function getId()
		{
			Assert::isNotNull($this->pageId);
			Assert::isNotNull($this->rightId);
			return $this->getPageId().'_'.$this->getRightId();
		}
		
		/**
		 * @return AutoPageRight
		 */
		public function setPageId($pageId)
		{
			$this->pageId = $pageId;
			return $this;
		}
		
		public function getPageId()
		{
			return $this->pageId;
		}
		
		/**
		 * @return AutoPageRight
		 */
		public function setPage(Page $page)
		{
			$this->pageId = $page->getId();
			return $this;
		}
		
		/**
		 * @return Page
		 */
		public function getPage()
		{
			return Page::da()->getById($this->getPageId());
		}
		
		/**
		 * @return AutoPageRight
		 */
		public function setRightId($rightId)
		{
			$this->rightId = $rightId;
			return $this;
		}
		
		public function getRightId()
		{
			return $this->rightId;
		}
		
		/**
		 * @return AutoPageRight
		 */
		public function setRight(Right $right)
		{
			$this->rightId = $right->getId();
			return $this;
		}
		
		/**
		 * @return Right
		 */
		public function getRight()
		{
			return Right::da()->getById($this->getRightId());
		}
		
		/**
		 * @return AutoPageRight
		 */
		public function setRedirectPageId($redirectPageId)
		{
			$this->redirectPageId = $redirectPageId;
			return $this;
		}
		
		public function getRedirectPageId()
		{
			return $this->redirectPageId;
		}
		
		/**
		 * @return AutoPageRight
		 */
		public function setRedirectPage(Page $redirectPage)
		{
			$this->redirectPageId = $redirectPage->getId();
			return $this;
		}
		
		/**
		 * @return Page
		 */
		public function getRedirectPage()
		{
			return Page::da()->getById($this->getRedirectPageId());
		}
	}
?>