<?php
	/* $Id$ */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	class AutoNavigation
	{
		private $id = null;
		
		private $categoryId = null;
		
		private $uri = null;
		
		/**
		 * @return NavigationDA
		 */
		public static function da()
		{
			return NavigationDA::me();
		}
		
		/**
		 * @return AutoNavigation
		 */
		public function setId($id)
		{
			$this->id = $id;
			return $this;
		}
		
		public function getId()
		{
			Assert::isNotNull($this->id);
			return $this->id;
		}
		
		/**
		 * @return AutoNavigation
		 */
		public function setCategoryId($categoryId)
		{
			$this->categoryId = $categoryId;
			return $this;
		}
		
		public function getCategoryId()
		{
			Assert::isNotNull($this->categoryId);
			return $this->categoryId;
		}
		
		/**
		 * @return Category
		 */
		public function getCategory()
		{
			return Category::da()->getById($this->getCategoryId());
		}
		
		/**
		 * @return AutoNavigation
		 */
		public function setUri($uri)
		{
			$this->uri = $uri;
			return $this;
		}
		
		public function getUri()
		{
			Assert::isNotNull($this->uri);
			return $this->uri;
		}
	}
?>