<?php
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoDebugData
	{
		private $id = null;
		
		private $session = null;
		
		/**
		 * @var array
		 */
		private $data = null;
		
		private $date = null;
		
		/**
		 * @return DebugDataDA
		 */
		public static function da()
		{
			return DebugDataDA::me();
		}
		
		/**
		 * @return AutoDebugData
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}
		
		public function getId()
		{
			Assert::isNotNull($this->id);
			return $this->id;
		}
		
		/**
		 * @return AutoDebugData
		 */
		public function setSession($session = null)
		{
			$this->session = $session;

			return $this;
		}
		
		public function getSession()
		{
			return $this->session;
		}
		
		/**
		 * @return AutoDebugData
		 */
		public function setData(array $data)
		{
			$this->data = $data;

			return $this;
		}
		
		/**
		 * @return array
		 */
		public function getData()
		{
			return $this->data;
		}
		
		/**
		 * @return AutoDebugData
		 */
		public function setDate($date)
		{
			$this->date = $date;

			return $this;
		}
		
		public function getDate()
		{
			return $this->date;
		}
	}
?>