<?php
	/* $Id$ */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoLayout
	{
		private $id = null;
		
		private $viewFileId = null;
		
		/**
		 * @return LayoutDA
		 */
		public static function da()
		{
			return LayoutDA::me();
		}
		
		/**
		 * @return AutoLayout
		 */
		public function setId($id)
		{
			$this->id = $id;
			return $this;
		}
		
		public function getId()
		{
			Assert::isNotNull($this->id);
			return $this->id;
		}
		
		/**
		 * @return AutoLayout
		 */
		public function setViewFileId($viewFileId)
		{
			$this->viewFileId = $viewFileId;
			return $this;
		}
		
		public function getViewFileId()
		{
			return $this->viewFileId;
		}
		
		/**
		 * @return AutoLayout
		 */
		public function setViewFile(ViewFile $viewFile)
		{
			$this->viewFileId = $viewFile->getId();
			return $this;
		}
		
		/**
		 * @return ViewFile
		 */
		public function getViewFile()
		{
			return ViewFile::da()->getById($this->getViewFileId());
		}
	}
?>