<?php
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageModule
	{
		private $id = null;
		
		private $pageId = null;
		
		/**
		 * @var Page
		 */
		private $page = null;
		
		private $moduleId = null;
		
		/**
		 * @var Module
		 */
		private $module = null;
		
		private $section = null;
		
		private $position = null;
		
		private $priority = null;
		
		/**
		 * @var array
		 */
		private $settings = null;
		
		private $viewFileId = null;
		
		/**
		 * @var ViewFile
		 */
		private $viewFile = null;
		
		/**
		 * @return PageModuleDA
		 */
		public static function da()
		{
			return PageModuleDA::me();
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}
		
		public function getId()
		{
			Assert::isNotNull($this->id);
			return $this->id;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setPageId($pageId)
		{
			$this->page = null;
			$this->pageId = $pageId;

			return $this;
		}
		
		public function getPageId()
		{
			return $this->pageId;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setPage(Page $page)
		{
			$this->pageId = $page->getId();
			$this->page = $page;

			return $this;
		}
		
		/**
		 * @return Page
		 */
		public function getPage()
		{
			if (!$this->page && $this->getPageId())
				$this->page = Page::da()->getById($this->getPageId());
				
			return $this->page;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setModuleId($moduleId)
		{
			$this->module = null;
			$this->moduleId = $moduleId;

			return $this;
		}
		
		public function getModuleId()
		{
			return $this->moduleId;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setModule(Module $module)
		{
			$this->moduleId = $module->getId();
			$this->module = $module;

			return $this;
		}
		
		/**
		 * @return Module
		 */
		public function getModule()
		{
			if (!$this->module && $this->getModuleId())
				$this->module = Module::da()->getById($this->getModuleId());
				
			return $this->module;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setSection($section = null)
		{
			$this->section = $section;

			return $this;
		}
		
		public function getSection()
		{
			return $this->section;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setPosition($position = null)
		{
			$this->position = $position;

			return $this;
		}
		
		public function getPosition()
		{
			return $this->position;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setPriority($priority = null)
		{
			$this->priority = $priority;

			return $this;
		}
		
		public function getPriority()
		{
			return $this->priority;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setSettings(array $settings = null)
		{
			$this->settings = $settings;

			return $this;
		}
		
		/**
		 * @return array
		 */
		public function getSettings()
		{
			return $this->settings;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setViewFileId($viewFileId = null)
		{
			$this->viewFile = null;
			$this->viewFileId = $viewFileId;

			return $this;
		}
		
		public function getViewFileId()
		{
			return $this->viewFileId;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setViewFile(ViewFile $viewFile = null)
		{
			$this->viewFileId = $viewFile->getId();
			$this->viewFile = $viewFile;

			return $this;
		}
		
		/**
		 * @return ViewFile
		 */
		public function getViewFile()
		{
			if (!$this->viewFile && $this->getViewFileId())
				$this->viewFile = ViewFile::da()->getById($this->getViewFileId());
				
			return $this->viewFile;
		}
	}
?>