<?php
	namespace ewgraCms;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageData
	{
		private $id = null;

		private $pageId = null;

		/**
		 * @var Page
		 */
		private $page = null;

		private $languageId = null;

		/**
		 * @var Language
		 */
		private $language = null;

		private $title = null;

		private $description = null;

		private $keywords = null;

		/**
		 * @return PageDataDA
		 */
		public static function da()
		{
			return PageDataDA::me();
		}

		/**
		 * @return AutoPageData
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}

		public function getId()
		{
			\ewgraFramework\Assert::isNotNull($this->id);
			return $this->id;
		}

		/**
		 * @return AutoPageData
		 */
		public function setPageId($pageId)
		{
			$this->page = null;
			$this->pageId = $pageId;

			return $this;
		}

		public function getPageId()
		{
			return $this->pageId;
		}

		/**
		 * @return AutoPageData
		 */
		public function setPage(Page $page)
		{
			$this->pageId = $page->getId();
			$this->page = $page;

			return $this;
		}

		/**
		 * @return Page
		 */
		public function getPage()
		{
			if (!$this->page && $this->getPageId())
				$this->page = Page::da()->getById($this->getPageId());

			return $this->page;
		}

		/**
		 * @return AutoPageData
		 */
		public function setLanguageId($languageId)
		{
			$this->language = null;
			$this->languageId = $languageId;

			return $this;
		}

		public function getLanguageId()
		{
			return $this->languageId;
		}

		/**
		 * @return AutoPageData
		 */
		public function setLanguage(Language $language)
		{
			$this->languageId = $language->getId();
			$this->language = $language;

			return $this;
		}

		/**
		 * @return Language
		 */
		public function getLanguage()
		{
			if (!$this->language && $this->getLanguageId())
				$this->language = Language::da()->getById($this->getLanguageId());

			return $this->language;
		}

		/**
		 * @return AutoPageData
		 */
		public function setTitle($title = null)
		{
			$this->title = $title;

			return $this;
		}

		public function getTitle()
		{
			return $this->title;
		}

		/**
		 * @return AutoPageData
		 */
		public function setDescription($description = null)
		{
			$this->description = $description;

			return $this;
		}

		public function getDescription()
		{
			return $this->description;
		}

		/**
		 * @return AutoPageData
		 */
		public function setKeywords($keywords = null)
		{
			$this->keywords = $keywords;

			return $this;
		}

		public function getKeywords()
		{
			return $this->keywords;
		}
	}
?>