<?php
	/* $Id$ */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoViewFile
	{
		private $id = null;
		
		/**
		 * @var ContentType
		 */
		private $contentType = null;
		
		private $path = null;
		
		/**
		 * @var boolean
		 */
		private $joinable = null;
		
		/**
		 * @return ViewFileDA
		 */
		public static function da()
		{
			return ViewFileDA::me();
		}
		
		/**
		 * @return AutoViewFile
		 */
		public function setId($id)
		{
			$this->id = $id;
			return $this;
		}
		
		public function getId()
		{
			Assert::isNotNull($this->id);
			return $this->id;
		}
		
		/**
		 * @return AutoViewFile
		 */
		public function setContentType(ContentType $contentType)
		{
			$this->contentType = $contentType;
			return $this;
		}
		
		/**
		 * @return ContentType
		 */
		public function getContentType()
		{
			Assert::isNotNull($this->contentType);
			return $this->contentType;
		}
		
		/**
		 * @return AutoViewFile
		 */
		public function setPath($path)
		{
			$this->path = $path;
			return $this;
		}
		
		public function getPath()
		{
			Assert::isNotNull($this->path);
			return $this->path;
		}
		
		/**
		 * @return AutoViewFile
		 */
		public function setJoinable($joinable = true)
		{
			$this->joinable = ($joinable === true);
			return $this;
		}
		
		/**
		 * @return boolean
		 */
		public function getJoinable()
		{
			return $this->joinable;
		}
		
		public function isJoinable()
		{
			return ($this->getJoinable() === true);
		}
	}
?>