<?php
	/* $Id$ */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	class AutoPage
	{
		private $id = null;
		
		private $path = null;
		
		/**
		 * @var boolean
		 */
		private $preg = null;
		
		private $layoutId = null;
		
		/**
		 * @var PageStatus
		 */
		private $status = null;
		
		private $modified = null;
		
		/**
		 * @return PageDA
		 */
		public static function da()
		{
			return PageDA::me();
		}
		
		/**
		 * @return AutoPage
		 */
		public function setId($id)
		{
			$this->id = $id;
			return $this;
		}
		
		public function getId()
		{
			Assert::isNotNull($this->id);
			return $this->id;
		}
		
		/**
		 * @return AutoPage
		 */
		public function setPath($path)
		{
			$this->path = $path;
			return $this;
		}
		
		public function getPath()
		{
			Assert::isNotNull($this->path);
			return $this->path;
		}
		
		/**
		 * @return AutoPage
		 */
		public function setPreg($preg = true)
		{
			$this->preg = ($preg === true);
			return $this;
		}
		
		/**
		 * @return boolean
		 */
		public function getPreg()
		{
			return $this->preg;
		}
		
		public function isPreg()
		{
			return ($this->getPreg() === true);
		}
		
		/**
		 * @return AutoPage
		 */
		public function setLayoutId($layoutId)
		{
			$this->layoutId = $layoutId;
			return $this;
		}
		
		public function getLayoutId()
		{
			Assert::isNotNull($this->layoutId);
			return $this->layoutId;
		}
		
		/**
		 * @return Layout
		 */
		public function getLayout()
		{
			return Layout::da()->getById($this->getLayoutId());
		}
		
		/**
		 * @return AutoPage
		 */
		public function setStatus(PageStatus $status)
		{
			$this->status = $status;
			return $this;
		}
		
		/**
		 * @return PageStatus
		 */
		public function getStatus()
		{
			Assert::isNotNull($this->status);
			return $this->status;
		}
		
		/**
		 * @return AutoPage
		 */
		public function setModified($modified)
		{
			$this->modified = $modified;
			return $this;
		}
		
		public function getModified()
		{
			Assert::isNotNull($this->modified);
			return $this->modified;
		}
	}
?>