<?php
	/* $Id$ */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageModule
	{
		private $pageId = null;
		
		private $moduleId = null;
		
		private $section = null;
		
		private $position = null;
		
		private $priority = null;
		
		/**
		 * @var array
		 */
		private $settings = null;
		
		private $viewFileId = null;
		
		/**
		 * @return PageModuleDA
		 */
		public static function da()
		{
			return PageModuleDA::me();
		}
		
		public function getId()
		{
			return $this->getPageId().'_'.$this->getPageId().'_'.$this->getModuleId().'_'.$this->getModuleId().'_'.$this->getSection().'_'.$this->getPosition();
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setPageId($pageId)
		{
			$this->pageId = $pageId;
			return $this;
		}
		
		public function getPageId()
		{
			Assert::isNotNull($this->pageId);
			return $this->pageId;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setPage(Page $page)
		{
			$this->pageId = $page->getId();
			return $this;
		}
		
		/**
		 * @return Page
		 */
		public function getPage()
		{
			return Page::da()->getById($this->getPageId());
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setModuleId($moduleId)
		{
			$this->moduleId = $moduleId;
			return $this;
		}
		
		public function getModuleId()
		{
			Assert::isNotNull($this->moduleId);
			return $this->moduleId;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setModule(Module $module)
		{
			$this->moduleId = $module->getId();
			return $this;
		}
		
		/**
		 * @return Module
		 */
		public function getModule()
		{
			return Module::da()->getById($this->getModuleId());
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setSection($section)
		{
			$this->section = $section;
			return $this;
		}
		
		public function getSection()
		{
			return $this->section;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setPosition($position)
		{
			$this->position = $position;
			return $this;
		}
		
		public function getPosition()
		{
			return $this->position;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setPriority($priority)
		{
			$this->priority = $priority;
			return $this;
		}
		
		public function getPriority()
		{
			return $this->priority;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setSettings(array $settings = null)
		{
			$this->settings = $settings;
			return $this;
		}
		
		/**
		 * @return array
		 */
		public function getSettings()
		{
			return $this->settings;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setViewFileId($viewFileId)
		{
			$this->viewFileId = $viewFileId;
			return $this;
		}
		
		public function getViewFileId()
		{
			return $this->viewFileId;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setViewFile(ViewFile $viewFile = null)
		{
			$this->viewFileId = $viewFile->getId();
			return $this;
		}
		
		/**
		 * @return ViewFile
		 */
		public function getViewFile()
		{
			return ViewFile::da()->getById($this->getViewFileId());
		}
	}
?>