<?php
	/* $Id$ */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageData
	{
		private $pageId = null;
		
		private $languageId = null;
		
		private $title = null;
		
		private $description = null;
		
		private $keywords = null;
		
		/**
		 * @return PageDataDA
		 */
		public static function da()
		{
			return PageDataDA::me();
		}
		
		public function getId()
		{
			return $this->getPageId().'_'.$this->getPageId().'_'.$this->getLanguageId().'_'.$this->getLanguageId();
		}
		
		/**
		 * @return AutoPageData
		 */
		public function setPageId($pageId)
		{
			$this->pageId = $pageId;
			return $this;
		}
		
		public function getPageId()
		{
			Assert::isNotNull($this->pageId);
			return $this->pageId;
		}
		
		/**
		 * @return Page
		 */
		public function getPage()
		{
			return Page::da()->getById($this->getPageId());
		}
		
		/**
		 * @return AutoPageData
		 */
		public function setLanguageId($languageId)
		{
			$this->languageId = $languageId;
			return $this;
		}
		
		public function getLanguageId()
		{
			Assert::isNotNull($this->languageId);
			return $this->languageId;
		}
		
		/**
		 * @return Language
		 */
		public function getLanguage()
		{
			return Language::da()->getById($this->getLanguageId());
		}
		
		/**
		 * @return AutoPageData
		 */
		public function setTitle($title)
		{
			$this->title = $title;
			return $this;
		}
		
		public function getTitle()
		{
			return $this->title;
		}
		
		/**
		 * @return AutoPageData
		 */
		public function setDescription($description)
		{
			$this->description = $description;
			return $this;
		}
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return AutoPageData
		 */
		public function setKeywords($keywords)
		{
			$this->keywords = $keywords;
			return $this;
		}
		
		public function getKeywords()
		{
			return $this->keywords;
		}
	}
?>