<?php
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageModule
	{
		private $id = null;
		
		private $pageId = null;
		
		private $moduleId = null;
		
		private $section = null;
		
		private $position = null;
		
		private $priority = null;
		
		/**
		 * @var array
		 */
		private $settings = null;
		
		private $viewFileId = null;
		
		/**
		 * @return PageModuleDA
		 */
		public static function da()
		{
			return PageModuleDA::me();
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setId($id)
		{
			$this->id = $id;
			return $this;
		}
		
		public function getId()
		{
			Assert::isNotNull($this->id);
			return $this->id;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setPageId($pageId)
		{
			$this->pageId = $pageId;
			return $this;
		}
		
		public function getPageId()
		{
			return $this->pageId;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setPage(Page $page)
		{
			$this->pageId = $page->getId();
			return $this;
		}
		
		/**
		 * @return Page
		 */
		public function getPage()
		{
			return Page::da()->getById($this->getPageId());
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setModuleId($moduleId)
		{
			$this->moduleId = $moduleId;
			return $this;
		}
		
		public function getModuleId()
		{
			return $this->moduleId;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setModule(Module $module)
		{
			$this->moduleId = $module->getId();
			return $this;
		}
		
		/**
		 * @return Module
		 */
		public function getModule()
		{
			return Module::da()->getById($this->getModuleId());
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setSection($section = null)
		{
			$this->section = $section;
			return $this;
		}
		
		public function getSection()
		{
			return $this->section;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setPosition($position = null)
		{
			$this->position = $position;
			return $this;
		}
		
		public function getPosition()
		{
			return $this->position;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setPriority($priority = null)
		{
			$this->priority = $priority;
			return $this;
		}
		
		public function getPriority()
		{
			return $this->priority;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setSettings(array $settings = null)
		{
			$this->settings = $settings;
			return $this;
		}
		
		/**
		 * @return array
		 */
		public function getSettings()
		{
			return $this->settings;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setViewFileId($viewFileId = null)
		{
			$this->viewFileId = $viewFileId;
			return $this;
		}
		
		public function getViewFileId()
		{
			return $this->viewFileId;
		}
		
		/**
		 * @return AutoPageModule
		 */
		public function setViewFile(ViewFile $viewFile = null)
		{
			$this->viewFileId = $viewFile->getId();
			return $this;
		}
		
		/**
		 * @return ViewFile
		 */
		public function getViewFile()
		{
			return ViewFile::da()->getById($this->getViewFileId());
		}
	}
?>