<?php
	namespace ewgraCms;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class Page extends AutoPage
	{
		/**
		 * @return Page
		 */
		public static function create()
		{
			return new self;
		}

		public function getUrlMatches(\ewgraFramework\HttpUrl $url)
		{
			preg_match(
				'@'.str_replace('@', '\@', $this->getPath()).'@',
				urldecode($url->getPath()),
				$matches
			);

			return $matches;
		}

		public function getData(Language $language)
		{
			return PageData::da()->get($this, $language);
		}
	}
?>