<?php
	namespace ewgraCms;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoControllerProto extends \ewgraFramework\ProtoObject
	{
		protected $dbFields = array(
			"id" =>  "id", 
			"name" =>  "name", 
			"settings" =>  "settings"
		);
	}
?>