<?php
	namespace ewgraCms;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageProto extends \ewgraFramework\ProtoObject
	{
		protected $dbFields = array(
			"id" =>  "id", 
			"path" =>  "path", 
			"preg" =>  "preg", 
			"layout" =>  "layout_id", 
			"layoutSettings" =>  "layout_settings", 
			"status" =>  "status", 
			"modified" =>  "modified"
		);
	}
?>