<?php
	namespace ewgraCms;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageDataProto extends \ewgraFramework\ProtoObject
	{
		protected $dbFields = array(
			"id" =>  "id", 
			"page" =>  "page_id", 
			"language" =>  "language_id", 
			"title" =>  "title", 
			"description" =>  "description", 
			"keywords" =>  "keywords"
		);
	}
?>