<?php
	namespace ewgraCms;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageControllerProto extends \ewgraFramework\ProtoObject
	{
		protected $dbFields = array(
			"id" =>  "id", 
			"page" =>  "page_id", 
			"controller" =>  "controller_id", 
			"section" =>  "section", 
			"position" =>  "position", 
			"priority" =>  "priority", 
			"settings" =>  "settings", 
			"viewFile" =>  "view_file_id"
		);
	}
?>