<?php
	/* $Id */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoViewFileDA extends CmsDatabaseRequester
	{
		protected $tableAlias = 'ViewFile';
		
		/**
		 * @return ViewFile
		 */		
		public function insert(ViewFile $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParams = array();
			
			if ($object->hasContentType())) {
				$dbQuery .= 'content_type = ?';
				$queryParams[] = $object->getContentType()->getId();
			}
			
			if ($object->hasPath())) {
				$dbQuery .= 'path = ?';
				$queryParams[] = $object->getPath();
			}
			
			if ($object->hasJoinable())) {
				$dbQuery .= 'joinable = ?';
				$queryParams[] = $object->getJoinable()->getId();
			}
			
			$this->db()->query($dbQuery, $queryParams);
			 
			$object->setId($this->db()->getInsertedId());
			
			return $object;
		}

		/**
		 * @return ViewFile
		 */
		protected function build(array $array)
		{
			return
				ViewFile::create()->
					setId($array['id'])->
					setContentType(ContentType::create($array['content_type']))->
					setPath(Config::me()->replaceVariables($array['path']))->
					setJoinable($array['joinable'] == 1);
		}

	}
?>