<?php
	/* $Id */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoLayoutDA extends CmsDatabaseRequester
	{
		protected $tableAlias = 'Layout';
		
		/**
		 * @return Layout
		 */		
		public function insert(Layout $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParams = array();
			
			if ($object->hasViewFileId())) {
				$dbQuery .= 'view_file_id = ?';
				$queryParams[] = $object->getViewFileId();
			}
			
			$this->db()->query($dbQuery, $queryParams);
			 
			$object->setId($this->db()->getInsertedId());
			
			return $object;
		}

		/**
		 * @return Layout
		 */
		protected function build(array $array)
		{
			return
				Layout::create()->
					setId($array['id'])->
					setViewFileId($array['view_file_id']);
		}

	}
?>