<?php
	/* $Id */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoDebugDataDA extends CmsDatabaseRequester
	{
		protected $tableAlias = 'DebugData';
		
		/**
		 * @return DebugData
		 */		
		public function insert(DebugData $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParams = array();
			
			if ($object->hasSession())) {
				$dbQuery .= 'session = ?';
				$queryParams[] = $object->getSession();
			}
			
			if ($object->hasData())) {
				$dbQuery .= 'data = ?';
				$queryParams[] = serialize($object->getData());
			}
			
			if ($object->hasDate())) {
				$dbQuery .= 'date = ?';
				$queryParams[] = $object->getDate();
			}
			
			$this->db()->query($dbQuery, $queryParams);
			 
			$object->setId($this->db()->getInsertedId());
			
			return $object;
		}

		/**
		 * @return DebugData
		 */
		protected function build(array $array)
		{
			return
				DebugData::create()->
					setId($array['id'])->
					setSession($array['session'])->
					setData($array['data'] ? unserialize($array['data']) : null)->
					setDate($array['date']);
		}
	}
?>