<?php
	namespace ewgraCms;
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageControllerDA extends DatabaseRequester
	{
		protected $tableAlias = 'PageController';
		
		/**
		 * @return PageController
		 */
		public function insert(PageController $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParts = array();
			$queryParams = array();
			
			if (!is_null($object->getPageId())) {
				$queryParts[] = '`page_id` = ?';
				$queryParams[] = $object->getPageId();
			}
			
			if (!is_null($object->getControllerId())) {
				$queryParts[] = '`controller_id` = ?';
				$queryParams[] = $object->getControllerId();
			}
			
			if (!is_null($object->getSection())) {
				$queryParts[] = '`section` = ?';
				$queryParams[] = $object->getSection();
			}
			
			if (!is_null($object->getPosition())) {
				$queryParts[] = '`position` = ?';
				$queryParams[] = $object->getPosition();
			}
			
			if (!is_null($object->getPriority())) {
				$queryParts[] = '`priority` = ?';
				$queryParams[] = $object->getPriority();
			}
			
			if (!is_null($object->getSettings())) {
				$queryParts[] = '`settings` = ?';
				$queryParams[] = serialize($object->getSettings());
			}
			
			if (!is_null($object->getViewFileId())) {
				$queryParts[] = '`view_file_id` = ?';
				$queryParams[] = $object->getViewFileId();
			}
			
			$dbQuery .= join(', ', $queryParts);
			
			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);
			
			$object->setId($this->db()->getInsertedId());
			
			$this->dropCache();
			
			return $object;
		}

		/**
		 * @return AutoPageControllerDA
		 */
		public function save(PageController $object)
		{
			$dbQuery = 'UPDATE '.$this->getTable().' SET ';
			
			$queryParts = array();
			$whereParts = array();
			$queryParams = array();
			
			$queryParts[] = '`page_id` = ?';
			$queryParams[] = $object->getPageId();
			$queryParts[] = '`controller_id` = ?';
			$queryParams[] = $object->getControllerId();
			
			if ($object->getSection() === null)
				$queryParts[] = '`section` = NULL';
			else {
				$queryParts[] = '`section` = ?';
				$queryParams[] = $object->getSection();
			}
			
			
			if ($object->getPosition() === null)
				$queryParts[] = '`position` = NULL';
			else {
				$queryParts[] = '`position` = ?';
				$queryParams[] = $object->getPosition();
			}
			
			
			if ($object->getPriority() === null)
				$queryParts[] = '`priority` = NULL';
			else {
				$queryParts[] = '`priority` = ?';
				$queryParams[] = $object->getPriority();
			}
			
			
			if ($object->getSettings() === null)
				$queryParts[] = '`settings` = NULL';
			else {
				$queryParts[] = '`settings` = ?';
				$queryParams[] = serialize($object->getSettings());
			}
			
			
			if ($object->getViewFileId() === null)
				$queryParts[] = '`view_file_id` = NULL';
			else {
				$queryParts[] = '`view_file_id` = ?';
				$queryParams[] = $object->getViewFileId();
			}
			
			
			$whereParts[] = 'id = ?';
			$queryParams[] = $object->getId();
			\ewgraFramework\Assert::isNotEmpty($whereParts);
			
			$dbQuery .= join(', ', $queryParts).' WHERE '.join(' AND ', $whereParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);
			 
			$this->dropCache();
			
			return $object;
		}

		/**
		 * @return AutoPageControllerDA
		 */
		public function delete(PageController $object)
		{
			$dbQuery =
				'DELETE FROM '.$this->getTable().' WHERE id = '.$object->getId();
			
			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->setQuery($dbQuery)
			);
			 
			$object->setId(null);
			
			$this->dropCache();
			
			return $this;
		}

		public function getById($id)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id = ?')->
				setValues(array($id))
			);
		}
		
		public function getByIds(array $ids)
		{
			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id IN(?)')->
				setValues(array($ids))
			);
		}
		
		/**
		 * @return PageController
		 */
		public function build(array $array)
		{
			return
				PageController::create()->
				setId($array['id'])->
				setPageId($array['page_id'])->
				setControllerId($array['controller_id'])->
				setSection($array['section'])->
				setPosition($array['position'])->
				setPriority($array['priority'])->
				setSettings($array['settings'] ? unserialize($array['settings']) : null)->
				setViewFileId($array['view_file_id']);
		}
	}
?>