<?php
	namespace ewgraCms;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageDA extends DatabaseRequester
	{
		protected $tableAlias = 'page';

		/**
		 * @return Page
		 */
		public function insert(Page $object)
		{
			$dialect = $this->db()->getDialect();

			$dbQuery = 'INSERT INTO '.$this->getTable().' ';
			$fields = array();
			$fieldValues = array();
			$values = array();
			$fields[] = $dialect->escapeField('path');
			$fieldValues[] = '?';
			$values[] = $object->getPath();
			$fields[] = $dialect->escapeField('preg');
			$fieldValues[] = '?';

			if ($object->getPreg() === null)
				$values[] = null;
			else {
				$values[] = $object->getPreg();
			}

			$fields[] = $dialect->escapeField('layout_id');
			$fieldValues[] = '?';
			$values[] = $object->getLayoutId();
			$fields[] = $dialect->escapeField('layout_settings');
			$fieldValues[] = '?';

			if ($object->getLayoutSettings() === null)
				$values[] = null;
			else {
				$values[] = serialize($object->getLayoutSettings());
			}

			$fields[] = $dialect->escapeField('status');
			$fieldValues[] = '?';
			$values[] = $object->getStatus()->getId();
			$fields[] = $dialect->escapeField('modified');
			$fieldValues[] = '?';
			$values[] = $object->getModified();
			$dbQuery .= '('.join(', ', $fields).') VALUES ';
			$dbQuery .= '('.join(', ', $fieldValues).')';

			$dbResult =
				$this->db()->insertQuery(
					\ewgraFramework\DatabaseInsertQuery::create()->
					setPrimaryField('id')->
					setQuery($dbQuery)->
					setValues($values)
				);

			$object->setId($dbResult->getInsertedId());

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoPageDA
		 */
		public function save(Page $object)
		{
			$dialect = $this->db()->getDialect();
			$dbQuery = 'UPDATE '.$this->getTable().' SET ';

			$queryParts = array();
			$whereParts = array();
			$queryParams = array();

			$queryParts[] = $dialect->escapeField('path').' = ?';
			$queryParams[] = $object->getPath();

			if ($object->getPreg() === null)
				$queryParts[] = $dialect->escapeField('preg').' = NULL';
			else {
				$queryParts[] = $dialect->escapeField('preg').' = ?';
				$queryParams[] = $object->getPreg();
			}

			$queryParts[] = $dialect->escapeField('layout_id').' = ?';
			$queryParams[] = $object->getLayoutId();

			if ($object->getLayoutSettings() === null)
				$queryParts[] = $dialect->escapeField('layout_settings').' = NULL';
			else {
				$queryParts[] = $dialect->escapeField('layout_settings').' = ?';
				$queryParams[] = serialize($object->getLayoutSettings());
			}

			$queryParts[] = $dialect->escapeField('status').' = ?';
			$queryParams[] = $object->getStatus()->getId();
			$queryParts[] = $dialect->escapeField('modified').' = ?';
			$queryParams[] = $object->getModified();

			$whereParts[] = 'id = ?';
			$queryParams[] = $object->getId();
			\ewgraFramework\Assert::isNotEmpty($whereParts);

			$dbQuery .= join(', ', $queryParts).' WHERE '.join(' AND ', $whereParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoPageDA
		 */
		public function delete(Page $object)
		{
			$dbQuery =
				'DELETE FROM '.$this->getTable().' WHERE id = '.$object->getId();

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->setQuery($dbQuery)
			);

			$object->setId(null);

			$this->dropCache();

			return $this;
		}

		public function getById($id)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id = ?')->
				setValues(array($id))
			);
		}

		public function getByIds(array $ids)
		{
			if (!$ids)
				return array();

			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id IN(?)')->
				setValues(array($ids))
			);
		}

		/**
		 * @return Page
		 */
		public function build(array $array)
		{
			return
				Page::create()->
				setId($array['id'])->
				setPath($array['path'])->
				setPreg($array['preg'] === null ? null : $array['preg'] == true)->
				setLayoutId($array['layout_id'])->
				setLayoutSettings($array['layout_settings'] ? unserialize($array['layout_settings']) : null)->
				setStatus(PageStatus::create($array['status']))->
				setModified($array['modified']);
		}

		public function dropCache()
		{
			PageData::da()->dropCache();
			PageController::da()->dropCache();
			return parent::dropCache();
		}
	}
?>