<?php
	/* $Id */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoContentDA extends CmsDatabaseRequester
	{
		protected $tableAlias = 'Content';
		
		/**
		 * @return Content
		 */		
		public function insert(Content $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParams = array();
			
			if ($object->hasStatus())) {
				$dbQuery .= 'status = ?';
				$queryParams[] = $object->getStatus()->getId();
			}
			
			$this->db()->query($dbQuery, $queryParams);
			 
			$object->setId($this->db()->getInsertedId());
			
			return $object;
		}

		/**
		 * @return Content
		 */
		protected function build(array $array)
		{
			return
				Content::create()->
					setId($array['id'])->
					setStatus(ContentStatus::create($array['status']));
		}

	}
?>