<?php
	/* $Id */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoRightDA extends CmsDatabaseRequester
	{
		protected $tableAlias = 'Right';
		
		/**
		 * @return Right
		 */		
		public function insert(Right $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParts = array();
			$queryParams = array();
			
			if (!is_null($object->getAlias())) {
				$queryParts[] = 'alias = ?';
				$queryParams[] = $object->getAlias();
			}
			
			if (!is_null($object->getName())) {
				$queryParts[] = 'name = ?';
				$queryParams[] = $object->getName();
			}
			
			if (!is_null($object->getRole())) {
				$queryParts[] = 'role = ?';
				$queryParams[] = $object->getRole()->getId();
			}
			
			$dbQuery .= join(', ', $queryParts);
			$this->db()->query($dbQuery, $queryParams);
			 
			$object->setId($this->db()->getInsertedId());
			
			$this->dropCache();
			
			return $object;
		}

		/**
		 * @return Right
		 */
		protected function build(array $array)
		{
			return
				Right::create()->
					setId($array['id'])->
					setAlias($array['alias'])->
					setName($array['name'])->
					setRole($array['role'] == 1);
		}
	}
?>