<?php
	namespace ewgraCms;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageControllerDA extends DatabaseRequester
	{
		protected $tableAlias = 'page_controller';

		public function getTag()
		{
			return '\ewgraCms\PageController';
		}

		/**
		 * @return array
		 */
		public function getTagList()
		{
			return array($this->getTag(), '\ewgraCms\Page', '\ewgraCms\Controller', '\ewgraCms\ViewFile');
		}

		/**
		 * @return PageController
		 */
		public function insert(PageController $object)
		{
			$result = $this->rawInsert($object);
			$this->dropCache();
			return $result;
		}

		/**
		 * @return PageController
		 */
		public function rawInsert(PageController $object)
		{
			$dialect = $this->db()->getDialect();

			$dbQuery = 'INSERT INTO '.$this->getTable().' ';
			$fields = array();
			$fieldValues = array();
			$values = array();

			if ($object->hasId()) {
				$fields[] = $dialect->escapeField('id');
				$fieldValues[] = '?';
				$values[] = $object->getId();
			}

			$fields[] = $dialect->escapeField('page_id');
			$fieldValues[] = '?';
			$values[] = $object->getPageId();
			$fields[] = $dialect->escapeField('controller_id');
			$fieldValues[] = '?';
			$values[] = $object->getControllerId();
			$fields[] = $dialect->escapeField('section');
			$fieldValues[] = '?';

			if ($object->getSection() === null)
				$values[] = null;
			else {
				$values[] = $object->getSection();
			}

			$fields[] = $dialect->escapeField('position');
			$fieldValues[] = '?';

			if ($object->getPosition() === null)
				$values[] = null;
			else {
				$values[] = $object->getPosition();
			}

			$fields[] = $dialect->escapeField('priority');
			$fieldValues[] = '?';

			if ($object->getPriority() === null)
				$values[] = null;
			else {
				$values[] = $object->getPriority();
			}

			$fields[] = $dialect->escapeField('settings');
			$fieldValues[] = '?';

			if ($object->getSettings() === null)
				$values[] = null;
			else {
				$values[] = serialize($object->getSettings());
			}

			$fields[] = $dialect->escapeField('view_file_id');
			$fieldValues[] = '?';

			if ($object->getViewFileId() === null)
				$values[] = null;
			else {
				$values[] = $object->getViewFileId();
			}

			$dbQuery .= '('.join(', ', $fields).') VALUES ';
			$dbQuery .= '('.join(', ', $fieldValues).')';

			$dbResult =
				$this->db()->insertQuery(
					\ewgraFramework\DatabaseInsertQuery::create()->
					setPrimaryField('id')->
					setQuery($dbQuery)->
					setValues($values)
				);

			if (!$object->hasId())
				$object->setId($dbResult->getInsertedId());

			return $object;
		}

		/**
		 * @return AutoPageControllerDA
		 */
		public function save(PageController $object)
		{
			$result = $this->rawSave($object);
			$this->dropCache();
			return $result;
		}

		/**
		 * @return AutoPageControllerDA
		 */
		public function rawSave(PageController $object)
		{
			$dialect = $this->db()->getDialect();
			$dbQuery = 'UPDATE '.$this->getTable().' SET ';

			$queryParts = array();
			$whereParts = array();
			$queryParams = array();

			$queryParts[] = $dialect->escapeField('page_id').' = ?';
			$queryParams[] = $object->getPageId();
			$queryParts[] = $dialect->escapeField('controller_id').' = ?';
			$queryParams[] = $object->getControllerId();

			if ($object->getSection() === null)
				$queryParts[] = $dialect->escapeField('section').' = NULL';
			else {
				$queryParts[] = $dialect->escapeField('section').' = ?';
				$queryParams[] = $object->getSection();
			}


			if ($object->getPosition() === null)
				$queryParts[] = $dialect->escapeField('position').' = NULL';
			else {
				$queryParts[] = $dialect->escapeField('position').' = ?';
				$queryParams[] = $object->getPosition();
			}


			if ($object->getPriority() === null)
				$queryParts[] = $dialect->escapeField('priority').' = NULL';
			else {
				$queryParts[] = $dialect->escapeField('priority').' = ?';
				$queryParams[] = $object->getPriority();
			}


			if ($object->getSettings() === null)
				$queryParts[] = $dialect->escapeField('settings').' = NULL';
			else {
				$queryParts[] = $dialect->escapeField('settings').' = ?';
				$queryParams[] = serialize($object->getSettings());
			}


			if ($object->getViewFileId() === null)
				$queryParts[] = $dialect->escapeField('view_file_id').' = NULL';
			else {
				$queryParts[] = $dialect->escapeField('view_file_id').' = ?';
				$queryParams[] = $object->getViewFileId();
			}


			$whereParts[] = 'id = ?';
			$queryParams[] = $object->getId();
			\ewgraFramework\Assert::isNotEmpty($whereParts);

			$dbQuery .= join(', ', $queryParts).' WHERE '.join(' AND ', $whereParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);

			return $object;
		}

		/**
		 * @return AutoPageControllerDA
		 */
		public function delete(PageController $object)
		{
			$result = $this->rawDelete($object);
			$this->dropCache();
			return $result;
		}

		/**
		 * @return AutoPageControllerDA
		 */
		public function rawDelete(PageController $object)
		{
			$dbQuery =
				'DELETE FROM '.$this->getTable().' WHERE id = '.$object->getId();

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->setQuery($dbQuery)
			);

			$object->setId(null);

			return $this;
		}

		public function getById($id)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id = ?')->
				setValues(array($id))
			);
		}

		public function getByIds(array $ids)
		{
			if (!$ids)
				return array();

			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id IN(?)')->
				setValues(array($ids))
			);
		}

		/**
		 * @return PageController
		 */
		public function build(array $array)
		{
			return
				PageController::create()->
				setId($array['id'])->
				setPageId($array['page_id'])->
				setControllerId($array['controller_id'])->
				setSection($array['section'])->
				setPosition($array['position'])->
				setPriority($array['priority'])->
				setSettings($array['settings'] ? unserialize($array['settings']) : null)->
				setViewFileId($array['view_file_id']);
		}
	}
?>