<?php
	/* $Id */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoCategoryDA extends CmsDatabaseRequester
	{
		protected $tableAlias = 'Category';
		
		/**
		 * @return Category
		 */		
		public function insert(Category $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParts = array();
			$queryParams = array();
			
			if (!is_null($object->getAlias())) {
				$queryParts[] = 'alias = ?';
				$queryParams[] = $object->getAlias();
			}
			
			$dbQuery .= join(', ', $queryParts);
			$this->db()->query($dbQuery, $queryParams);
			
			$object->setId($this->db()->getInsertedId());
			
			$this->dropCache();
			
			return $object;
		}

		/**
		 * @return AutoCategoryDA
		 */		
		public function save(Category $object)
		{
			$dbQuery = 'UPDATE '.$this->getTable().' SET ';
			$queryParts = array();
			$whereParts = array();
			$queryParams = array();
			
			$queryParts[] = 'alias = ?';
			$queryParams[] = $object->getAlias();
			
			$whereParts = array();
			
			$whereParts[] = 'id = ?';
			$queryParams[] = $object->getId();
			
			$dbQuery .= join(', ', $queryParts). ' WHERE '.join(' AND ', $whereParts);
			$this->db()->query($dbQuery, $queryParams);
			 
			$this->dropCache();
			
			return $object;
		}

		/**
		 * @return Category
		 */
		protected function build(array $array)
		{
			return
				Category::create()->
					setId($array['id'])->
					setAlias($array['alias']);
		}
	}
?>