<?php
	/* $Id */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageDataDA extends CmsDatabaseRequester
	{
		protected $tableAlias = 'PageData';
		
		/**
		 * @return PageData
		 */		
		public function insert(PageData $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParams = array();
			
			if ($object->hasPageId())) {
				$dbQuery .= 'page_id = ?';
				$queryParams[] = $object->getPageId();
			}
			
			if ($object->hasLanguageId())) {
				$dbQuery .= 'language_id = ?';
				$queryParams[] = $object->getLanguageId();
			}
			
			if ($object->hasTitle())) {
				$dbQuery .= 'title = ?';
				$queryParams[] = $object->getTitle();
			}
			
			if ($object->hasDescription())) {
				$dbQuery .= 'description = ?';
				$queryParams[] = $object->getDescription();
			}
			
			if ($object->hasKeywords())) {
				$dbQuery .= 'keywords = ?';
				$queryParams[] = $object->getKeywords();
			}
			
			$this->db()->query($dbQuery, $queryParams);
			 
			$object->setId($this->db()->getInsertedId());
			
			return $object;
		}

		/**
		 * @return PageData
		 */
		protected function build(array $array)
		{
			return
				PageData::create()->
					setPageId($array['page_id'])->
					setLanguageId($array['language_id'])->
					setTitle($array['title'])->
					setDescription($array['description'])->
					setKeywords($array['keywords']);
		}
	}
?>