<?php
	/* $Id */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageDA extends CmsDatabaseRequester
	{
		protected $tableAlias = 'Page';
		
		/**
		 * @return Page
		 */		
		public function insert(Page $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParams = array();
			
			if (!is_null($object->getPath())) {
				$dbQuery .= 'path = ?';
				$queryParams[] = $object->getPath();
			}
			
			if (!is_null($object->getPreg())) {
				$dbQuery .= 'preg = ?';
				$queryParams[] = $object->getPreg()->getId();
			}
			
			if (!is_null($object->getLayoutId())) {
				$dbQuery .= 'layout_id = ?';
				$queryParams[] = $object->getLayoutId();
			}
			
			if (!is_null($object->getStatus())) {
				$dbQuery .= 'status = ?';
				$queryParams[] = $object->getStatus()->getId();
			}
			
			if (!is_null($object->getModified())) {
				$dbQuery .= 'modified = ?';
				$queryParams[] = $object->getModified();
			}
			
			$this->db()->query($dbQuery, $queryParams);
			 
			$object->setId($this->db()->getInsertedId());
			
			return $object;
		}

		/**
		 * @return Page
		 */
		protected function build(array $array)
		{
			return
				Page::create()->
					setId($array['id'])->
					setPath($array['path'])->
					setPreg($array['preg'] == 1)->
					setLayoutId($array['layout_id'])->
					setStatus(PageStatus::create($array['status']))->
					setModified($array['modified']);
		}
	}
?>