<?php
	namespace ewgraCms;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoControllerDA extends DatabaseRequester
	{
		protected $tableAlias = 'controller';

		/**
		 * @return Controller
		 */
		public function insert(Controller $object)
		{
			$dialect = $this->db()->getDialect();

			$dbQuery = 'INSERT INTO '.$this->getTable().' ';
			$fields = array();
			$fieldValues = array();
			$values = array();
			$fields[] = $dialect->escapeField('name');
			$fieldValues[] = '?';
			$values[] = $object->getName();
			$fields[] = $dialect->escapeField('settings');
			$fieldValues[] = '?';

			if ($object->getSettings() === null)
				$values[] = null;
			else {
				$values[] = serialize($object->getSettings());
			}

			$dbQuery .= '('.join(', ', $fields).') VALUES ';
			$dbQuery .= '('.join(', ', $fieldValues).')';

			$dbResult =
				$this->db()->insertQuery(
					\ewgraFramework\DatabaseInsertQuery::create()->
					setPrimaryField('id')->
					setQuery($dbQuery)->
					setValues($values)
				);

			$object->setId($dbResult->getInsertedId());

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoControllerDA
		 */
		public function save(Controller $object)
		{
			$dialect = $this->db()->getDialect();
			$dbQuery = 'UPDATE '.$this->getTable().' SET ';

			$queryParts = array();
			$whereParts = array();
			$queryParams = array();

			$queryParts[] = $dialect->escapeField('name').' = ?';
			$queryParams[] = $object->getName();

			if ($object->getSettings() === null)
				$queryParts[] = $dialect->escapeField('settings').' = NULL';
			else {
				$queryParts[] = $dialect->escapeField('settings').' = ?';
				$queryParams[] = serialize($object->getSettings());
			}


			$whereParts[] = 'id = ?';
			$queryParams[] = $object->getId();
			\ewgraFramework\Assert::isNotEmpty($whereParts);

			$dbQuery .= join(', ', $queryParts).' WHERE '.join(' AND ', $whereParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoControllerDA
		 */
		public function delete(Controller $object)
		{
			$dbQuery =
				'DELETE FROM '.$this->getTable().' WHERE id = '.$object->getId();

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->setQuery($dbQuery)
			);

			$object->setId(null);

			$this->dropCache();

			return $this;
		}

		public function getById($id)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id = ?')->
				setValues(array($id))
			);
		}

		public function getByIds(array $ids)
		{
			if (!$ids)
				return array();

			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id IN(?)')->
				setValues(array($ids))
			);
		}

		/**
		 * @return Controller
		 */
		public function build(array $array)
		{
			return
				Controller::create()->
				setId($array['id'])->
				setName($array['name'])->
				setSettings($array['settings'] ? unserialize($array['settings']) : null);
		}

		public function dropCache()
		{
			PageController::da()->dropCache();
			return parent::dropCache();
		}
	}
?>