<?php
	/* $Id */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageRightDA extends CmsDatabaseRequester
	{
		protected $tableAlias = 'PageRight';
		
		/**
		 * @return PageRight
		 */		
		public function insert(PageRight $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParams = array();
			
			if ($object->hasPageId())) {
				$dbQuery .= 'page_id = ?';
				$queryParams[] = $object->getPageId();
			}
			
			if ($object->hasRightId())) {
				$dbQuery .= 'right_id = ?';
				$queryParams[] = $object->getRightId();
			}
			
			if ($object->hasRedirectPageId())) {
				$dbQuery .= 'redirect_page_id = ?';
				$queryParams[] = $object->getRedirectPageId();
			}
			
			$this->db()->query($dbQuery, $queryParams);
			 
			$object->setId($this->db()->getInsertedId());
			
			return $object;
		}

		/**
		 * @return PageRight
		 */
		protected function build(array $array)
		{
			return
				PageRight::create()->
					setPageId($array['page_id'])->
					setRightId($array['right_id'])->
					setRedirectPageId($array['redirect_page_id']);
		}
	}
?>