<?php
	/* $Id */
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoContentDataDA extends CmsDatabaseRequester
	{
		protected $tableAlias = 'ContentData';
		
		/**
		 * @return ContentData
		 */		
		public function insert(ContentData $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParams = array();
			
			if ($object->hasContentId())) {
				$dbQuery .= 'content_id = ?';
				$queryParams[] = $object->getContentId();
			}
			
			if ($object->hasLanguageId())) {
				$dbQuery .= 'language_id = ?';
				$queryParams[] = $object->getLanguageId();
			}
			
			if ($object->hasText())) {
				$dbQuery .= 'text = ?';
				$queryParams[] = $object->getText();
			}
			
			$this->db()->query($dbQuery, $queryParams);
			 
			$object->setId($this->db()->getInsertedId());
			
			return $object;
		}

		/**
		 * @return ContentData
		 */
		protected function build(array $array)
		{
			return
				ContentData::create()->
					setContentId($array['content_id'])->
					setLanguageId($array['language_id'])->
					setText($array['text']);
		}

	}
?>