<?php
	namespace ewgraCms;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class PageControllerDA extends AutoPageControllerDA
	{
		/**
		 * @return PageControllerDA
		 */
		public static function me()
		{
			return parent::getInstance(__CLASS__);
		}

		public function getByPage(Page $page)
		{
			$dbQuery = "
				SELECT * FROM ".$this->getTable()." WHERE page_id = ?
				ORDER BY priority, priority IS NULL
			";
			
			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues(array($page->getId()))
			);
		}
	}
?>