<?php
	namespace ewgraCms;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class PageControllerDA extends AutoPageControllerDA
	{
		/**
		 * @return PageControllerDA
		 * method needed for methods hinting
		 */
		public static function me()
		{
			return parent::me();
		}

		public function getByPage(Page $page)
		{
			$dialect = $this->db()->getDialect();

			$dbQuery = "
				SELECT * FROM ".$this->getTable()." WHERE page_id = ?
				ORDER BY "
					.$dialect->createOrder('priority')->toString($dialect).", "
					.$dialect->createOrder('position')->toString($dialect);

			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues(array($page->getId()))
			);
		}
	}
?>